Fix git usage with rbtools 6.0
rbtools.clients.errors.SCMError: Either GitClient.setup() or GitClient.has_dependencies() must be called before other functions are used.